endpoint:
  frontend:
    domain: ${FRONTEND_DOMAIN}
    o-auth2-sign-in: /sign-in/streaming-service
    o-auth2-callback: /sign-in/callback
  api:
    name: api
    label: API Server
    domain: http://localhost:${API_SERVER_PORT}
  spotify:
    name: spotify
    label: Spotify
    domain: https://api.spotify.com/v1
    max-idle-time: 50

spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}