CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    username   VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE streaming_service
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_streaming_service PRIMARY KEY (id)
);

CREATE TABLE streaming_service_user
(
    user_id                   BIGINT       NOT NULL,
    service_id                INTEGER      NOT NULL,
    streaming_service_user_id VARCHAR(100) NOT NULL,
    CONSTRAINT pk_streamingserviceuser PRIMARY KEY (service_id, streaming_service_user_id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE streaming_service
    ADD CONSTRAINT uc_streaming_service_name UNIQUE (name);

ALTER TABLE streaming_service_user
    ADD CONSTRAINT uc_streamingserviceuser_user UNIQUE (user_id);

ALTER TABLE streaming_service_user
    ADD CONSTRAINT FK_STREAMINGSERVICEUSER_ON_SERVICE FOREIGN KEY (service_id) REFERENCES streaming_service (id);

ALTER TABLE streaming_service_user
    ADD CONSTRAINT FK_STREAMINGSERVICEUSER_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);