CREATE TABLE jukebox
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    handle     VARCHAR(20)                             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_jukebox PRIMARY KEY (id)
);

ALTER TABLE jukebox
    ADD CONSTRAINT uc_jukebox_handle UNIQUE (handle);

ALTER TABLE jukebox
    ADD CONSTRAINT uc_jukebox_user UNIQUE (user_id);

ALTER TABLE jukebox
    ADD CONSTRAINT FK_JUKEBOX_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);