import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { Header } from "./_components/Header"
import Providers from "./providers"
import { Player } from "./_components/player/Player"
import { getServerSession } from "@/lib/auth/server"

const sans = Geist({
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
})

// TODO: 메타데이터 설정하기
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en" className={sans.variable}>
      <body>
        <Toaster richColors theme="system" position="top-center" />
        <Providers session={session}>
          <Header />
          <main>{children}</main>
          <Player />
        </Providers>
      </body>
    </html>
  )
}
